### PR TITLE
Added whitelist based on independent user-id

### PR DESCRIPTION
**Pull request by YourgenAP**
Updates:

1. vorpv2.sql - WHITELIST table changed auto-increment from 10 to 1, added extra column status
2. config.lua - Webhook for whitelist, langs "NoInWhitelist"
3. sv_apicontroller.lua - EventHandlers for whitelisting and unwhitelisting
4. sv_commands.lua - Commands _wlplayer_ and _unwlplayer_ with suggestions available from RedM client only for admins and mods and server command-line
5. sv_logs.lua - Webhook call for actions with whitelist
6. sv_whitelist - functional whitelist handling

Whitelist:

1. Based on id from _whitelist_ SQL-table
2. Connection based on steamidentiefier gets user-id for whitelist from extra table IdentifiersToIds which is also based on identiefiers and ids from _whitelist_ SQL-table
3. Extra column is real current status of user: whitelisted or not
4. SQL-table always updated on each action with whitelist
5. Thanks to extra column player will not be whitelisted or unwhitelisted on autoupdates (if they are enabled) or after restarts

### CODE REVIEW

**Comment by outsider31000** [comment]
if i understand correctly a player gets whitelisted if they are in gam and when an admin uses the command? @YourgenAP

**Comment by YourgenAP** [comment]
@outsider31000 
Player gets whitelistied when admin or mod uses the command but player is not obligatory to be in game. He needs to handshake  with server, get his user-id and send it to discord (or anywhere else, so it will not get lost). Admin can later whitelist the user at any time using just this user-id. And this user-id is the same as id in _whitelist_ Database.

**Comment by outsider31000** [comment]
I see.  so for the player to be whitelisted an admin needs to execute the command in the game and he does not need to be there?
so the player will not enter the server if he is not whitelisted correct? @YourgenAP

**Comment by YourgenAP** [comment]
@outsider31000 
Absolutelly correct. As long as player is not whitelisted after handshaking with server he will get kicked with reason NoInWhitelist from config.lua. Also, player can be unwhitelisted with executing the /unwlplayer command and next time player handshakes server he will get kicked with reason NoInWhitelist, which can be good for cooldowns (on so-called hardRP servers when changing characters) or if player broke the rules

**Comment by outsider31000** [comment]
right.

as a **suggestion** would it not be easier to check if the user has a whitelisted role in discord instead of using a command every time in game?

**Comment by YourgenAP** [comment]
I'm not sure how it works with discord roles and what is required to check players's discord and check his/her roles, so I have implemented it using only lua and sql which requires only to handshake with server, which seems to me much easier and more proven way of whitelisting

**Comment by outsider31000** [comment]
no problem  i will merge this thank you

**Pull request merged**
