### PR TITLE
Reduced to a loop, local spawn removed.

### PR DESCRIPTION
**Pull request by DerHobbs**
One loop is enough, 2 are not necessary, tested several times.

### CODE REVIEW

**Comment by RealStonerGamer** [comment]
but does pulling people off houses when pvp is true brake now ? and can other ride with you when pvp is true? i think this is why it was reverted the other day 

did you test that by chance?

**Comment by DerHobbs** [comment]
> but does pulling people off houses when pvp is true brake now ? and can other ride with you when pvp is true? i think this is why it was reverted the other day
> 
> did you test that by chance?

Yes, you can drive carriages or ride horses together even if PvP = true

**Comment by RealStonerGamer** [comment]
ok but when you stand next to house and hold e or f can you pull the rider off still or is it getting stuck half way in animation that is what happened when we were testing the other day

**Comment by RealStonerGamer** [comment]
if so then awesome !

**Comment by outsider31000** [comment]
the reason why they were separated is because of the optimisation.
adding the state bag to a while loop will bring resmon to 0.10ms.
also the input press has a wait during that Wait the controlls wont be disabled.

**Comment by outsider31000** [comment]
if there aren't no issues, it needs to stay as it is, for optimisation purposes.

**Pull request closed without merging**
