### PR TITLE
Essentials Update

### PR DESCRIPTION
**Pull request by AnishBplayz**
My pull request (PR) aims to incorporate essential features that are necessary for the core functionality. These features have been tested by me and have been in active use.

The changes are as Mentioned:

- Added a Config Option for Multiple Discord Rich Presence Buttons
- Added a Config to Save Discord User ID in DB
- Added a debug for ``vorp:ImDead`` Event since it some times fails to fetch Players Character Data
- Modified the ``userData.addCharacter`` function to return number of characters 
(Its for a upcoming PR Related to Vorp Characters)
- Rest files are edited just for better space and tab indications

### CODE REVIEW

**Comment by outsider31000** [comment]
image
 you will get an error here if identifier is not found as you calling a function without cheking if identifier is valid or if it exists in users.
 leaving the way it was was fine.
 
 
image

this has 2 checks with same variable , and yet they do different things. add them toghether or change the variable to a discordID name

Also storing discord ids , will not be beneficial as you can get another discord and still have same steam identifier, so the discord if wont be updated.

im not opposed to this but there needs to be a logic to check if the discord id is still the same or not to updated it.

once you done this things I asked, Ill merge. thanks

**Comment by cl3i550n** [comment]
Suggestion... put in whitelist db too... i make this here in my version of core... but only in whitelist db.

**Comment by AnishBplayz** [comment]
The core concept here revolves around the storage of Discord IDs, offering a broad range of benefits for servers utilizing Discord for communication. By including Discord IDs in the data, it becomes significantly easier for developers to retrieve information about players connecting to the server, facilitating seamless player identification directly from the database. 

I've had some uncertainty about how to incorporate Discord IDs into the `self.getusedCharacters` data, which is why I haven't implemented it yet. However, it seems like a valuable addition to the Character function.

It's important to note that the primary key remains the Steam identifier, and any potential changes in Discord IDs wouldn't affect the operation of a completely blacklisted server. However, for a whitelisted or allowlisted server, having access to Discord IDs becomes essential for maintaining detailed player records.

**Comment by AnishBplayz** [comment]
> Suggestion... put in whitelist db too... i make this here in my version of core... but only in whitelist db.

Will implement it in there too

**Comment by outsider31000** [comment]
@AnishBplayz  thats my point if you store discord ids they will have a use case , hence why we need a logic to update it in case they have another discord, either way i think this only comes from discord accounts they they log in RedM so maybe if they did got another discord account it wouldnt still detect but its always a good thing to update it.
also im not sure but if there is a column in users table that doent exists on player first join it will give an error. as the sql call doesnt allow adding columns unless changed in there

**Comment by cl3i550n** [comment]
> @AnishBplayz thats my point if you store discord ids they will have a use case , hence why we need a logic to update it in case they have another discord, either way i think this only comes from discord accounts they they log in RedM so maybe if they did got another discord account it wouldnt still detect but its always a good thing to update it. also im not sure but if there is a column in users table that doent exists on player first join it will give an error. as the sql call doesnt allow adding columns unless changed in there

In my case, I set it so that whenever the user connects to the server, he takes his current discord and updates it in the whitelist table, this makes it easier for administrators to identify the user more quickly, and i put with my whitelist bot too. My bot check if user id fixed is same of db baseated discordID. If user put id correcly and discordID represent same in db, into permit enter in server.

**Comment by cl3i550n** [comment]
I prefer to avoid players who want to enter with discord XXX and use discord YYYY to whitelist... This person does not have good intentions.

**Comment by AnishBplayz** [comment]
Incorporating a webhook log to track any changes in Discord IDs would indeed be a prudent and sensible approach. It ensures that server administrators can stay informed about these changes and respond accordingly.

Regarding the impact of a player changing their Discord ID, it's worth noting that this aspect might not be a critical concern. The essence lies in having a Discord ID associated with specific perks on the server, and whether those perks carry over after a Discord ID change largely depends on how a script developer utilizes this Discord ID for identification within their script. The degree of continuity in a player's privileges in such a scenario hinges on the developer's implementation of this crucial identification element.

**Comment by AnishBplayz** [comment]
> I prefer to avoid players who want to enter with discord XXX and use discord YYYY to whitelist... This person does not have good intentions.

When exactly do you update the whitelist info of a player into your table ?

**Comment by cl3i550n** [comment]
> > I prefer to avoid players who want to enter with discord XXX and use discord YYYY to whitelist... This person does not have good intentions.
> 
> When exactly do you update the whitelist info of a player into your table ?

In SV_Whitelist.lua event "playerConnecting"

    local discordIdentity = GetPlayerIdentifierByType(_source, 'discord')
    local discordId = discordIdentity and discordIdentity:sub(9) or ""
    
    -- This broke user not have discord opened
    
        if discordId == nil then
        deferrals.done(T.NoDiscord)
        userEntering = false
        CancelEvent()
        return
    end
    
    playerWlId = InsertIntoWhitelist(steamIdentifier, discordId)
    
    now in insertIntoWhitelist(steamIdentifier, discordId) -- added parameter
    
    -- update db
        MySQL.prepare.await("INSERT INTO whitelist (identifier, status, firstconnection, discord) VALUES (?,?,?,?)", { steamIdentifier, false, true, discordId }, function(result) end)
        
        _whitelist[currentFreeId] = Whitelist(currentFreeId, identifier, false, true, discord)
        
in functions LoadWhitelist and SetUpdateWhitelistPolicy

_whitelist[v.id] = Whitelist(v.id, v.identifier, v.status, v.firstconnection, v.discord)
        
================

in sv_loadusers.lua

in LoadUser function

    else
        local getDiscord = GetPlayerIdentifierByType(source, 'discord')
        local discordId = string.sub(getDiscord, 9)
        --New User
        MySQL.insert("INSERT INTO users VALUES(?,?,?,?,?,?,?)", { identifier, "user", 0, 0, 0, "false", discordId })
        _users[identifier] = User(source, identifier, "user", 0, license)
        deferrals.done()
    end
    
    now in 'playerJoining' event
    
    local discordIdentity = GetPlayerIdentifierByType(_source, 'discord')
    local discordId = discordIdentity and discordIdentity:sub(9) or ""
    
    local isWhiteListed = MySQL.single.await('SELECT * FROM discord WHERE identifier = ?', { identifier })
    
        if not Config.Whitelist and not isWhiteListed then
        MySQL.insert.await("INSERT INTO whitelist (identifier, status, firstconnection, discord) VALUES (?,?,?,?)", { identifier, false, true, discordId })
        isWhiteListed = MySQL.single.await('SELECT * FROM whitelist WHERE identifier = ?', { identifier })
    end
    
    _whitelist[userid] = Whitelist(userid, identifier, false, true, discord)
    
        if entry.getFirstconnection() then
        local steamName = GetPlayerName(_source) or ""
        local message = string.format(Translation[Lang].addWebhook.whitelistid, steamName, identifier, discordId, userid)
        TriggerEvent("vorp_core:addWebhook", Translation[Lang].addWebhook.whitelistid1, Config.NewPlayerWebhook, message)

        entry.setFirstconnection(false)
    else
        local steamName = GetPlayerName(_source) or ""
        local message = string.format(Translation[Lang].addWebhook.oldwhitelistid, steamName, identifier, discordId, userid)
        TriggerEvent("vorp_core:addWebhook", Translation[Lang].addWebhook.oldwhitelistid1, Config.NewPlayerWebhook, message)
    end

**Comment by AnishBplayz** [comment]
@outsider31000 For such usage as the server requires they can just edit it as per their requirements

**Comment by cl3i550n** [comment]
> > I prefer to avoid players who want to enter with discord XXX and use discord YYYY to whitelist... This person does not have good intentions.
> 
> When exactly do you update the whitelist info of a player into your table ?

Feel free to improve the code I sent.

**Comment by outsider31000** [comment]
image
this isnt acceptable we will not have 3 tables filled with the same information i dont care where it goes, as long its only one created.

**Comment by AnishBplayz** [comment]
Wouldn't it be more efficient to simplify the process of sorting or searching for specific Discord IDs by copying them from Discord and directly querying them in any of the three tables? I firmly believe that these three tables contain invaluable information, and servers heavily reliant on Discord IDs for player-related functions would greatly appreciate this feature. Moreover, I'm confident that implementing such a functionality would have no adverse impact on server performance. It's essentially akin to incorporating Steam identifiers into the requisite tables for streamlined data storage of a user. Performing direct database sorting with Steam identifiers can be cumbersome, and consolidating them under a single variable should not pose significant challenges when integrated into the VORP core.

**Comment by outsider31000** [comment]
im not saying no to it, but having this in 3 diferent tables will not be accpeted 
image
characters already have it, so use it, dont use users nor whitelist tables

**Comment by outsider31000** [comment]
just leave for characters table

**Comment by AnishBplayz** [comment]
Sure if you say so

**Comment by outsider31000** [comment]
its better to have in one place.

**Comment by AnishBplayz** [comment]
With these adjustments, I believe my pull request is ready for merging. Please do let me know if any further modifications are necessary.

**Comment by cl3i550n** [comment]
nice!

**Comment by cl3i550n** [comment]
> With these adjustments, I believe my pull request is ready for merging. Please do let me know if any further modifications are necessary.

This is my sv_whitelisting.lua of folder class folder

---@class Whitelist


---@param id number
---@param identifier string
---@param status number
---@param firstconnection boolean
---@param discord number
---@return Whitelist
function Whitelist(id, identifier, status, firstconnection, discord)
    local self = {}

    self._id = id
    self._identifier = identifier
    self._status = status
    self._firstconnection = firstconnection
    self.discord = discord

    self.Id = function()
        return self._id
    end

    self.Identifier = function()
        return self._identifier
    end

    self.Status = function(value)
        if value ~= nil then
            self._status = value
            MySQL.query('UPDATE whitelist SET status = @status where id = @id',
                { ['@status'] = value, ['@id'] = self.Id() }, function(result) end)
        end
        return self._status
    end

    self.Firstconnection = function(value)
        if value ~= nil then
            self._firstconnection = value
            MySQL.query('UPDATE whitelist SET firstconnection = @firstconnection where id = @id',
                { ['@firstconnection'] = value, ['@id'] = self.Id() }, function(result) end)
        end
        return self._firstconnection
    end

    self.Discord = function(value)
        if value ~= nil then
            self.discord = value
            MySQL.query('UPDATE whitelist SET discord = @discord where id = @id',
                { ['@discord'] = value, ['@id'] = self.Id() }, function(result) end)
        end
        return self.discord
    end

    self.GetEntry = function()
        local whitelistData = {}

        whitelistData.getId = function()
            return self.Id()
        end

        whitelistData.getIdentifier = function()
            return self.Identifier()
        end

        whitelistData.getStatus = function()
            return self.Status()
        end

        whitelistData.setStatus = function(value)
            return self.Status(value)
        end

        whitelistData.getFirstconnection = function()
            return self.Firstconnection()
        end

        whitelistData.setFirstconnection = function(value)
            return self.Firstconnection(value)
        end

        whitelistData.setDiscord = function(value)
            return self.Discord(value)
        end

        whitelistData.getDiscord = function()
            return self.Discord()
        end

        return whitelistData
    end

    return self
end

**Comment by outsider31000** [comment]
image
this is till missing to check for users identifier if it exists before exectuting a function, leave how it was it was fine

**Comment by AnishBplayz** [comment]
@outsider31000 With this the PR should be good to merge

**Comment by outsider31000** [comment]
I assume this was tested ?

**Comment by AnishBplayz** [comment]
> I assume this was tested ?

Yes it was tested

**Comment by outsider31000** [comment]
great thanks.

**Comment by AnishBplayz** [comment]
> great thanks.

My Pleasure

**Pull request merged**
