### PR TITLE
Added functionality to allow for player gang ID

### PR DESCRIPTION
**Pull request by Kianimal**
Saves gang ID in database characters table, and added command for /addGang. All testing shows it working and updating correctly (updates in the same way jobs do - after a timed wait or on relog).

### CODE REVIEW

**Comment by Kianimal** [comment]
ALTER TABLE characters
ADD COLUMN gang_column_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;

Here is the SQL statement existing servers will need to add the column

**Comment by outsider31000** [comment]
This is fine but, the group column in `characters` is used for this, it is why you have `users table` group `column` so characters column can be used for other groups like gangs, it isnt just for admins.
For me this is duplicated code just with a different name. 
Group can be used the same way and really for anything else.

If you can see the point I'm trying to make.

**Comment by Kianimal** [comment]
I see what you mean. Well up to you, I feel this adds more functionality and lets people use the character group column for other things while not locking them out of having a gang option at the same time but it's your call!

**Comment by outsider31000** [comment]
Yeah I get it, but gangs are groups , that column is for that is just not called gangs I think people see it as an admin column but no, it is for groups, any groups.

**Comment by Kianimal** [comment]
I've literally only ever seen it used as an admin column. I guess if it's for gangs, maybe make that a little bit clearer?

My opinion, anyway.

**Comment by pratinha10** [comment]
A lot of scripts use group column to set payvip status, thats I suggested to create a gang one.

**Comment by outsider31000** [comment]
> A lot of scripts use group column to set payvip status, thats I suggested to create a gang one.

yeah but we not gonna add duplicated code cause one person uses it for something else. thats not how things work lol

**Comment by outsider31000** [comment]
I see the point , but theres a group column there, it can be used for that purpose. theres no need to add the same code for a different function when a gang is a group, the effort is appreciated ofc @Kianimal

**Pull request closed without merging**
