### PR TITLE
POTENTIAL fix for vorp:SaveHealth and vorp:SaveStamina

### PR DESCRIPTION
**Pull request by AndrewR3K**
THIS IS UNTESTED! NOT READY FOR YET.

**_What this changes:_**
- POTENTIAL fix for vorp:SaveHealth and vorp:SaveStamina

### CODE REVIEW

**Comment by kylemcshea** [comment]
The very long wait looks like it was a lazy way to ensure the thread only hits after player selects a character or has a ped actively being used on their client. Better way to do this I think is to check if player loaded & also Find a way to not be running a while loop throughout the entire time player is in game that's just lazy code

**Comment by AndrewR3K** [comment]
This was just a potential fix to code that is not mine, this is completely untested as I've been on vacation and did it while away. I believe this was fixed and am closing this PR. Thanks.

**Comment by outsider31000** [comment]
> The very long wait looks like it was a lazy way to ensure the thread only hits after player selects a character or has a ped actively being used on their client. Better way to do this I think is to check if player loaded & also Find a way to not be running a while loop throughout the entire time player is in game that's just lazy code

This is open source for anyone to make pull requests,  if you knowa better way why dont you make a pull request?? too lazy I guess?

**Comment by kylemcshea** [comment]
Say less

**Pull request closed without merging**
