### PR TITLE
Minor Update

### PR DESCRIPTION
**Pull request by AndrewR3K**
Minor readme and icon order change.

### CODE REVIEW

**Comment by andrezote92** [comment]
There is still an issue with the script. When interacting with other menus, the UI disappears and never shows again until the moment of reconnecting.

**Comment by outsider31000** [comment]
"with other menus"  what menus ?

**Comment by AndrewR3K** [comment]
> There is still an issue with the script. When interacting with other menus, the UI disappears and never shows again until the moment of reconnecting.

Whenever the radar disapears, the ui will as well. You can use /toggleui to have it show again.

**Comment by andrezote92** [comment]
With menus like the bank, store... With the /toggleui command, it returns, it's a good solution lol.

**Pull request merged**
