### PR TITLE
Bans and warns

### PR DESCRIPTION
**Pull request by YourgenAP**
Reinvention of wheel for bans and warns. Everything using user-ids (the same as for whitelists)

To update are 
cl_adminactions.lua
sv_commands.lua
sv_bans.lua
sv_logs.lua
sv_whitelist.lua
sv_loadusers.lua
vorpv2.sql
config.lua

Users with already created `users` database can edit their db tables without deleting and creating again with SQL Code below
```
ALTER TABLE `users`
ADD COLUMN `banneduntil` int(10) DEFAULT 0 AFTER `banned`
CHANGE `banned` `banned` BOOLEAN NOT NULL DEFAULT FALSE;
```

Also small fix for whitelist discord logs

### CODE REVIEW

**Comment by outsider31000** [comment]
image
 why was this deleted ?

**Comment by outsider31000** [comment]
oh i see you added back.

**Comment by outsider31000** [comment]
just to be sure has this been doubled-checked?  @YourgenAP

**Comment by YourgenAP** [comment]
@outsider31000 made many tests on my server. Everything was working fine.

**Comment by outsider31000** [comment]
can you update the version file and the fx manifest version too please so that others are notified @YourgenAP

**Comment by YourgenAP** [comment]
will do

**Comment by YourgenAP** [comment]
@outsider31000 I suppose is ready

**Comment by outsider31000** [comment]
@YourgenAP  did you delete the past versions? don't delete them they need to stay just add a new one on top

**Comment by YourgenAP** [comment]
image
@outsider31000 like this?

**Comment by outsider31000** [comment]
you must include a - in all of the text  I think

**Comment by YourgenAP** [comment]
@outsider31000 done

**Comment by outsider31000** [comment]
thank you for the hard work

**Pull request merged**
