### PR TITLE
missing "Config.UseCharPermission" in config file.

### PR DESCRIPTION
**Pull request by cl3i550n**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
missing "Config.UseCharPermission" in config file.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

### CODE REVIEW

**Comment by outsider31000** [comment]
its not missing it was removed, you also are adding back other variables that were removed

**Comment by cl3i550n** [comment]
> its not missing it was removed, you also are adding back other variables that were removed



> its not missing it was removed, you also are adding back other variables that were removed

image

**Comment by outsider31000** [comment]
its not missing , theres no where this being used. same as the other you added back like updatewhitelist this doesnt exists anymore 

image
just need to remove this was left by mistake.

**Comment by outsider31000** [comment]
image
 same for this

**Comment by cl3i550n** [comment]
> its not missing , theres no where this being used. same as the other you added back like updatewhitelist this doesnt exists anymore
> 
> image just need to remove this was left by mistake.

close my pr... thanks for esclareciment.

**Comment by outsider31000** [comment]
sure thank you for your concern. but we dont need it anymore.

**Pull request closed without merging**
