### PR TITLE
Fix the erros with new players

### PR DESCRIPTION
**Pull request by DerHobbs**
If someone triggers this event it could be possible that he awaits (example: Citizen.Await with promise) a response.
But the callback is only called if character details exists. So the promise from the example will never be resolved.
That is a bad design.
Better solution is to call the callback with nil if character details not exists, so the promise from the example will be resolved with nil. The caller should handle the "nil" case then.

### CODE REVIEW

**Comment by outsider31000** [comment]
this Events are old and should not be used.  look in vorp API docs for the new and maintained API @DerHobbs

**Comment by DerHobbs** [comment]
Yeah no thing, for me it fixes the error when new players join the server, if you don't need it then just close it ;)

**Comment by outsider31000** [comment]
what errors?

**Comment by outsider31000** [comment]
yeah that's cause there are scripts using old events.

**Pull request merged**
