### PR TITLE
Updates for whitelist, bans, API

### PR DESCRIPTION
**Pull request by YourgenAP**

### CODE REVIEW

**Comment by outsider31000** [comment]
I assume this was tested ?

**Comment by YourgenAP** [comment]
@outsider31000 worked fine on my development server. Also enabled back DiscordId with extra if and time to give cfx a chance to catch it as it works fine

**Comment by outsider31000** [comment]
okay, can you leave a zip? please ill give an extra test

**Comment by outsider31000** [comment]
i can just get it from your fork

**Comment by YourgenAP** [comment]
[VORP Core Update.zip](https://github.com/VORPCORE/vorp-core-lua/files/8934156/VORP.Core.Update.zip)
@outsider31000

**Pull request merged**
