### PR TITLE
Expose character data to client

### PR DESCRIPTION
**Pull request by CriMsOnN**
The idea here is to expose character data to the client so we prevent server events that can be checked on client before they sent to the server like job, currency. Of course that doesnt mean you dont need security server side.

### CODE REVIEW

**Comment by outsider31000** [comment]
Please Provide examples on how to use it.

This is a framework for everyone to use and  not for a single person. 
We have a documentation  for this purpose.

**Comment by CriMsOnN** [comment]
You are right i am sorry.
Here is a gist with a demonstration and how to use the new functions https://gist.github.com/CriMsOnN/cb02f14667345a9f05a8f942462dde94

Tell me if you need more examples.

**Comment by outsider31000** [comment]
I have allowed this although dont see the point . you say is to reduce server events but we witll need to use them to check for security .
 @CriMsOnN

**Comment by outsider31000** [comment]
if  I want to do things in client I still need to go to server for security and see if I am allowed to then comeback again to client to allow the palyer I dont really see what server events are we preventing from using this. the more code the core has the more is loaded into memmory.

**Pull request merged**
