### PR TITLE
Fixed SQL Statement for insert new User into DB

### PR DESCRIPTION
**Pull request by Zaickz**
Fixed SQL Statement for insert new User into DB. Removed unnecessary values because they have a default value in DB

### CODE REVIEW

**Comment by outsider31000** [comment]
can you show me what error you get?

**Comment by Zaickz** [comment]
okay nervermind. i just loaded the version again and then it worked. i think i messed up something.

**Comment by Zaickz** [comment]
Jm3MN0OsRASmInDHE67tzw

**Comment by outsider31000** [comment]
you missing a colum , its not the code

**Comment by outsider31000** [comment]
look in the premade sql file thats the one everyone should be using.

**Pull request closed without merging**
