### PR TITLE
added multichar permission on db | save steamname on dropped in db

### PR DESCRIPTION
**Pull request by RobiZona**
you can choose on db 'users' who can have multicharacter use 'false' or 'true'
when player dropped save in db 'character' steamname for fast search

### CODE REVIEW

**Comment by YourgenAP** [comment]
sv_loadusers line 114 can cause multiple issues: MaxChars is 5, player has 3 Chars, someone set to false charPerm and player can never choose a char and play on server.

IMO, it is not needed to add charPerms, as it is a literal try to substitute existing rule: only one char pro player or multiple chars pro player. Some servers allow only one char, some allow to play multiple chars. Why do I need as server runner extra charPerms?

**Comment by YourgenAP** [comment]
Moreover. sv_loadusers line 41. Why for new player you set charPerms always to false? If I'm new player on a server with multiple chars allowed, I would be never available to create one more char, if I wish to play more then one char

**Comment by outsider31000** [comment]
if I understand correctly his idea is to have some players be able to choose 5 chars and others have 1 char only. now, this could have been done through the database for each player and not in the config for all players. wityh a command for admins to add more chars for each players.

if what he did doesnt not make sense then i cant pr.

**Comment by outsider31000** [comment]
a false true statement is still for all players, the way I said above is the best way to go. this means you can have players  donate to the server r for example. *using tebex*

**Comment by YourgenAP** [comment]
@outsider31000 Probably you are right. But it requires the extension of current pr. There is no command to change it. As I wrote it above, line 41 literally blocks me from creating new chars on multi-char servers. If I want to allow all players create new chars, I have to call command for every new player.

All in allow, it requires a command to chang charPerms for admins, as well changes to config to make it possible to decide, if it should be allowed to create new chars or not by default

**Comment by outsider31000** [comment]
yeah i wasnt mentioning his pr.  i was saying that the right way was the one I said. and not his way.

**Comment by outsider31000** [comment]
allow for each char and a command for admins, this gives so much freedom in a server.

**Comment by YourgenAP** [comment]
@RobiZona database should be not accesible by admins. It only for server owners and (if extra needed) for server developers. As I wrote tagging outsider it makes too much effort on servers with policy allowing multiple characters

**Comment by RobiZona** [comment]
ok, i understand, if i put a command to change the permission would it be fine?

**Comment by YourgenAP** [comment]
@RobiZona command and updated config for servers who want multiple users by default

**Comment by RobiZona** [comment]
I'm almost done, do I make a new pr or save everything directly?

**Comment by outsider31000** [comment]
jus fix this one or make a new one whichever is best for you

**Comment by RobiZona** [comment]
finish
i'm working on inventory now

**Comment by outsider31000** [comment]
that looks better also 
image
 dont think this is needed theres only goning to be one sql file.

**Comment by outsider31000** [comment]
just add the false there and leave an sql short code to make it easier for others to run that code.
leave it here

**Comment by RobiZona** [comment]
i did it, in config i wrote "if you put true need to update sql" and in sql i put altertable, do you want only final version with char?

**Pull request merged**
