### PR TITLE
Improve Whitelist System

### PR DESCRIPTION
**Pull request by cl3i550n**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Motive for This Pull Request

- server/whitelist.lua
 - Added missing config `CheckDoubleAccounts` in Config.lua
 - Added new function `GetDiscordID` return the Discord ID
 - Fixes params of `Whitelist` funtion status replace `0` to `false` because SQL DB `status` is `TINYINT`
 - Added new config `DiscordIsRequired` in Config.lua
 - Functions `InsertIntoWhitelist`, `LoadWhitelist`, `SetUpdateWhitelistPolicy` have all params.
 - Reduce `Wait` in `SetUpdateWhitelistPolicy` for `2000` to work prorpety after `status` changed to `1`

- server/loadusers.lua
 - Only reflect and better code improve Discord ID called new function `GetDiscordID`
 - Fixes params of `Whitelist` funtion status replace `0` to `false` because SQL DB `status` is `TINYINT`

- server/class/whitelisting.lua
 - Added new call `VORPwl.getEntry(identifier).getDiscord()` for exemple to use.
 - Fix comment param to boolean `--@param status boolean`.
 - Added all necessaries self calls to discordid.
 
 - SQL Whitelist NEED independent
 
image

- SQL Whitelist not should not atreled with users table, its independent.
If user not enter in server, because save or call identifier in db?

 ```sql
 CONSTRAINT `FK_characters_whitelist` FOREIGN KEY (`identifier`) REFERENCES `vorpv2`.`users` (`identifier`) ON UPDATE CASCADE ON DELETE CASCADE;
 ```
 
 - Need Replate to
 ```sql
DROP TABLE IF EXISTS `whitelist`;
CREATE TABLE IF NOT EXISTS `whitelist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `discordid` varchar(255) DEFAULT '0',
  `firstconnection` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `identifier` (`identifier`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
```

### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
The changes proposed in this pull request are primarily aimed at enhancing the functionality and reliability of the server's whitelist management. Key improvements include the introduction of new configurations such DiscordIsRequired in Config.lua, which offer more control and flexibility in user management. The addition of the GetDiscordID function and the inclusion of discordid in the SQL database are significant steps towards integrating Discord authentication, making user verification more robust and streamlined.

Moreover, the corrections made to the Whitelist function parameters and the reduction of wait time in SetUpdateWhitelistPolicy are designed to improve the overall efficiency and accuracy of whitelist operations. These changes not only address current bugs and inconsistencies but also lay a foundation for more advanced features and updates in the future. Overall, the aim is to provide a more secure, efficient, and user-friendly experience for both administrators and users of the framework.

### Explain the necessity of these changes and how they will impact the framework or its users.
These changes are essential to address existing bugs, improve security, and enhance user management. By resolving whitelist issues and introducing new configurations, we ensure a more stable and efficient server operation. The integration of Discord ID into the whitelist process notably advances user verification, using Discord's widespread adoption for streamlined, secure access management.

Additionally, these updates facilitate the use of bots or external APIs for automated player authorization, reducing the need for constant staff presence and dependence only txadmin, giving more options for owner or dev.

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi

There are a few things that need to be changed in this PR. 
image
Let's suppose  I have 15k of data or more,  this will update at every 2 seconds 15k users, the wait needs to be increased or add a config so it will be up to the server to have lag or not. we dont want users to come into support channels asking why are they having `server thread hitchs` there's no need to update a large amount of data at every 2 seconds.

Another thing that cannot be removed is the constrain for the whitelist table

This is needed to ensure whitelist is cleaned if user from users table is deleted, without this, whitelist table will only increase
By deleting users from user table it will clean whitelist aswell making queries more performant and removing data no longer needed.

so if it's going to break the script creating errors I cannot merge this.

Let me know if you understand what I said and if you have questions about it.

Thanks for the contribution.

**Comment by cl3i550n** [comment]
> Hi
> 
> There are a few things that need to be changed in this PR. image Let's suppose I have 15k of data or more, this will update at every 2 seconds 15k users, the wait needs to be increased or add a config so it will be up to the server to have lag or not. we dont want users to come into support channels asking why are they having `server thread hitchs` there's no need to update a large amount of data at every 2 seconds.
> 
> Another thing that cannot be removed is the constrain for the whitelist table
> 
> This is needed to ensure whitelist is cleaned if user from users table is deleted, without this, whitelist table will only increase By deleting users from user table it will clean whitelist aswell making queries more performant and removing data no longer needed.
> 
> so if it's going to break the script creating errors I cannot merge this.
> 
> Let me know if you understand what I said and if you have questions about it.
> 
> Thanks for the contribution.

Got it, I'll fix it!

**Comment by cl3i550n** [comment]
Done!

- Rollback to 36000 in wait of `SetUpdateWhitelistPolicy`
- Added new function `CheckWhitelistStatusOnConnect` check in the moment the status of especific user entry.
- All work fine with constrain for the whitelist table.

**Comment by cl3i550n** [comment]
Done!
- All tested and works fine!

**Comment by outsider31000** [comment]
Hi again 

We still nedd to do some changes here that i noticed.
image
this function `LoadUser` is being used twice, Please remove the first one and the Wait.

image
This code doesnt really make sense , beacause theres no role check, having a discord account required when nothing is checking for roles is redundante. We will not make vorp core dependent on discord.
if user dont have discord it will return nil that should be enough. 

If you have Questions let me know
Thank you for the contribution.

**Comment by cl3i550n** [comment]
> Hi again
> 
> We still nedd to do some changes here that i noticed. image this function `LoadUser` is being used twice, Please remove the first one and the Wait.
> 
> image This code doesnt really make sense , beacause theres no role check, having a discord account required when nothing is checking for roles is redundante. We will not make vorp core dependent on discord. if user dont have discord it will return nil that should be enough.
> 
> If you have Questions let me know Thank you for the contribution.

Done! Thanks for appointments.

**Comment by cl3i550n** [comment]
- Removed discord required
- Removed load function, duplices.
- Puting load function in correct sequence

**Comment by outsider31000** [comment]
okay this sounds great thank you for the contribution.

**Pull request merged**
